### ISSUE TITLE
Limpiar layout

### ISSUE THREAD

**Issue by MQSCarlosEstrada** [CAEM6/InvoiceManagement#6]
Quitar **_TODO_** lo que no sea necesario del layout (color azul)
Hay HTML de fondo que no se "ve" relacionado a lo que se encuentra en azul

Dejar en el sidebar-menu (color rojo) los siguientes elementos:
Accounts, Suppliers, Invoices, Reports (agregar el texto y un icono)

Ruta archivo:
InvoiceManagement\Views\Shared\ _Layout.cshtml

![image](https://github.com/CAEM6/InvoiceManagement/assets/62304253/317716c0-2471-492d-931a-305e4adf73fa)

**Comment by KreatorMX** [comment]
Limpio y agregado las vistas correspondientes
